"""
refund-handler — Microservice Handler
Service ID: 8cbfedb0-f264-accc-79ac-1b1ea8e56e0c
Framework: Django
Generated by WorldMaker Code Generator
"""
import logging
import json
from datetime import datetime

logger = logging.getLogger("refund-handler")

# ── Metadata (for static analysis / AI discovery) ────────────────────
__metadata__ = {
    "microservice": "refund-handler",
    "service_id": "8cbfedb0-f264-accc-79ac-1b1ea8e56e0c",
    "language": "python",
    "framework": "Django",
    "generated_at": "2026-02-08T23:46:58.598433",
}


def health_check() -> dict:
    """Health check endpoint."""
    return {"status": "healthy", "service": "refund-handler", "timestamp": datetime.utcnow().isoformat()}


def handle_event(event: dict) -> dict:
    """Main handler — processes incoming events/requests.

    Args:
        event: Incoming event payload with action and data fields.

    Returns:
        Response dict with status and result.
    """
    action = event.get("action", "default")
    data = event.get("data", {})

    logger.info("Processing action=%s for %s", action, "refund-handler")

    try:
        result = _process(action, data)
        return {"status": "success", "action": action, "result": result}
    except Exception as exc:
        logger.error("Handler error in %s: %s", "refund-handler", exc)
        return {"status": "error", "action": action, "error": str(exc)}


def _process(action: str, data: dict) -> dict:
    """Internal processing logic."""
    return {
        "processed_by": "refund-handler",
        "action": action,
        "item_count": len(data),
        "timestamp": datetime.utcnow().isoformat(),
    }


if __name__ == "__main__":
    # Local test
    print(json.dumps(health_check(), indent=2))
    print(json.dumps(handle_event({"action": "test", "data": {"key": "value"}}), indent=2))
