/**
 * refund--2-consumer — Microservice Handler
 * Service ID: ceb81f9d-7914-c120-c8dc-d19f3e351128
 * Framework: Koa
 * Generated by WorldMaker Code Generator
 */

// Metadata for static analysis / AI discovery
export const __metadata__ = {
  microservice: "refund--2-consumer",
  service_id: "ceb81f9d-7914-c120-c8dc-d19f3e351128",
  language: "typescript",
  framework: "Koa",
};

interface Event {
  action: string;
  data: Record<string, unknown>;
}

interface Response {
  status: string;
  action: string;
  result?: Record<string, unknown>;
  error?: string;
}

export function healthCheck(): Record<string, string> {
  return {
    status: "healthy",
    service: "refund--2-consumer",
    timestamp: new Date().toISOString(),
  };
}

export function handleEvent(event: Event): Response {
  const { action = "default", data = {} } = event;

  console.log(`Processing action=${action} for refund--2-consumer`);

  try {
    const result = process(action, data);
    return { status: "success", action, result };
  } catch (err) {
    console.error(`Handler error in refund--2-consumer:`, err);
    return { status: "error", action, error: String(err) };
  }
}

function process(action: string, data: Record<string, unknown>): Record<string, unknown> {
  return {
    processed_by: "refund--2-consumer",
    action,
    item_count: Object.keys(data).length,
    timestamp: new Date().toISOString(),
  };
}

// Local test
if (require.main === module) {
  console.log(JSON.stringify(healthCheck(), null, 2));
  console.log(JSON.stringify(handleEvent({ action: "test", data: { key: "value" } }), null, 2));
}
