"""Code templates for microservice source repositories.

Provides realistic handler, Dockerfile, and dependency file templates
for 6 language/framework pairs.  Each template is a simple lambda-style
handler — realistic enough for static analysis, simple enough for the
generator to stamp out hundreds.
"""
from __future__ import annotations

from datetime import datetime
from typing import Any


# ── Template Registry ────────────────────────────────────────────────────

LANGUAGE_TEMPLATES: dict[str, dict[str, Any]] = {
    "python": {
        "frameworks": ["FastAPI", "Django", "Flask", "Celery"],
        "handler_file": "handler.py",
        "dep_file": "requirements.txt",
        "dockerfile_base": "python:3.12-slim",
        "ext": "py",
    },
    "go": {
        "frameworks": ["Gin", "Echo", "Fiber", "gRPC"],
        "handler_file": "main.go",
        "dep_file": "go.mod",
        "dockerfile_base": "golang:1.22-alpine",
        "ext": "go",
    },
    "java": {
        "frameworks": ["Spring Boot", "Micronaut", "Quarkus", "Vert.x"],
        "handler_file": "Handler.java",
        "dep_file": "pom.xml",
        "dockerfile_base": "eclipse-temurin:21-jre",
        "ext": "java",
    },
    "typescript": {
        "frameworks": ["NestJS", "Express", "Fastify", "Koa"],
        "handler_file": "handler.ts",
        "dep_file": "package.json",
        "dockerfile_base": "node:20-alpine",
        "ext": "ts",
    },
    "rust": {
        "frameworks": ["Actix", "Axum", "Rocket", "Warp"],
        "handler_file": "main.rs",
        "dep_file": "Cargo.toml",
        "dockerfile_base": "rust:1.75-slim",
        "ext": "rs",
    },
    "kotlin": {
        "frameworks": ["Ktor", "Spring Boot", "Micronaut"],
        "handler_file": "Application.kt",
        "dep_file": "build.gradle.kts",
        "dockerfile_base": "eclipse-temurin:21-jre",
        "ext": "kt",
    },
}


# ── Handler Templates ────────────────────────────────────────────────────

def _python_handler(ms: dict[str, Any]) -> str:
    name = ms.get("name", "unknown")
    service_id = ms.get("service_id", "unknown")
    framework = ms.get("framework", "FastAPI")
    return f'''"""
{name} — Microservice Handler
Service ID: {service_id}
Framework: {framework}
Generated by WorldMaker Code Generator
"""
import logging
import json
from datetime import datetime

logger = logging.getLogger("{name}")

# ── Metadata (for static analysis / AI discovery) ────────────────────
__metadata__ = {{
    "microservice": "{name}",
    "service_id": "{service_id}",
    "language": "python",
    "framework": "{framework}",
    "generated_at": "{datetime.utcnow().isoformat()}",
}}


def health_check() -> dict:
    """Health check endpoint."""
    return {{"status": "healthy", "service": "{name}", "timestamp": datetime.utcnow().isoformat()}}


def handle_event(event: dict) -> dict:
    """Main handler — processes incoming events/requests.

    Args:
        event: Incoming event payload with action and data fields.

    Returns:
        Response dict with status and result.
    """
    action = event.get("action", "default")
    data = event.get("data", {{}})

    logger.info("Processing action=%s for %s", action, "{name}")

    try:
        result = _process(action, data)
        return {{"status": "success", "action": action, "result": result}}
    except Exception as exc:
        logger.error("Handler error in %s: %s", "{name}", exc)
        return {{"status": "error", "action": action, "error": str(exc)}}


def _process(action: str, data: dict) -> dict:
    """Internal processing logic."""
    return {{
        "processed_by": "{name}",
        "action": action,
        "item_count": len(data),
        "timestamp": datetime.utcnow().isoformat(),
    }}


if __name__ == "__main__":
    # Local test
    print(json.dumps(health_check(), indent=2))
    print(json.dumps(handle_event({{"action": "test", "data": {{"key": "value"}}}}), indent=2))
'''


def _go_handler(ms: dict[str, Any]) -> str:
    name = ms.get("name", "unknown")
    service_id = ms.get("service_id", "unknown")
    framework = ms.get("framework", "Gin")
    return f'''// {name} — Microservice Handler
// Service ID: {service_id}
// Framework: {framework}
// Generated by WorldMaker Code Generator
package main

import (
\t"encoding/json"
\t"fmt"
\t"log"
\t"net/http"
\t"time"
)

// Metadata for static analysis / AI discovery
var metadata = map[string]string{{
\t"microservice": "{name}",
\t"service_id":   "{service_id}",
\t"language":     "go",
\t"framework":    "{framework}",
}}

type HealthResponse struct {{
\tStatus    string `json:"status"`
\tService   string `json:"service"`
\tTimestamp string `json:"timestamp"`
}}

type Event struct {{
\tAction string                 `json:"action"`
\tData   map[string]interface{{}} `json:"data"`
}}

type Response struct {{
\tStatus string      `json:"status"`
\tAction string      `json:"action"`
\tResult interface{{}} `json:"result"`
}}

func healthCheck(w http.ResponseWriter, r *http.Request) {{
\tresp := HealthResponse{{
\t\tStatus:    "healthy",
\t\tService:   "{name}",
\t\tTimestamp: time.Now().UTC().Format(time.RFC3339),
\t}}
\tjson.NewEncoder(w).Encode(resp)
}}

func handleEvent(w http.ResponseWriter, r *http.Request) {{
\tvar event Event
\tif err := json.NewDecoder(r.Body).Decode(&event); err != nil {{
\t\thttp.Error(w, err.Error(), http.StatusBadRequest)
\t\treturn
\t}}

\tlog.Printf("Processing action=%s for {name}", event.Action)

\tresult := map[string]interface{{}}{{
\t\t"processed_by": "{name}",
\t\t"action":       event.Action,
\t\t"item_count":   len(event.Data),
\t\t"timestamp":    time.Now().UTC().Format(time.RFC3339),
\t}}

\tresp := Response{{Status: "success", Action: event.Action, Result: result}}
\tjson.NewEncoder(w).Encode(resp)
}}

func main() {{
\thttp.HandleFunc("/health", healthCheck)
\thttp.HandleFunc("/handle", handleEvent)
\tfmt.Println("{name} listening on :8080")
\tlog.Fatal(http.ListenAndServe(":8080", nil))
}}
'''


def _java_handler(ms: dict[str, Any]) -> str:
    name = ms.get("name", "unknown")
    service_id = ms.get("service_id", "unknown")
    class_name = "".join(w.capitalize() for w in name.replace("-", " ").split())
    return f'''/**
 * {name} — Microservice Handler
 * Service ID: {service_id}
 * Generated by WorldMaker Code Generator
 */
package com.worldmaker.{name.replace("-", ".")};

import java.time.Instant;
import java.util.Map;
import java.util.HashMap;
import java.util.logging.Logger;

public class {class_name}Handler {{

    private static final Logger logger = Logger.getLogger("{name}");

    // Metadata for static analysis / AI discovery
    public static final Map<String, String> METADATA = Map.of(
        "microservice", "{name}",
        "service_id", "{service_id}",
        "language", "java",
        "framework", "{ms.get("framework", "Spring Boot")}"
    );

    public Map<String, Object> healthCheck() {{
        Map<String, Object> resp = new HashMap<>();
        resp.put("status", "healthy");
        resp.put("service", "{name}");
        resp.put("timestamp", Instant.now().toString());
        return resp;
    }}

    public Map<String, Object> handleEvent(Map<String, Object> event) {{
        String action = (String) event.getOrDefault("action", "default");
        Map<String, Object> data = (Map<String, Object>) event.getOrDefault("data", Map.of());

        logger.info("Processing action=" + action + " for {name}");

        try {{
            Map<String, Object> result = process(action, data);
            return Map.of("status", "success", "action", action, "result", result);
        }} catch (Exception e) {{
            logger.severe("Handler error: " + e.getMessage());
            return Map.of("status", "error", "action", action, "error", e.getMessage());
        }}
    }}

    private Map<String, Object> process(String action, Map<String, Object> data) {{
        Map<String, Object> result = new HashMap<>();
        result.put("processed_by", "{name}");
        result.put("action", action);
        result.put("item_count", data.size());
        result.put("timestamp", Instant.now().toString());
        return result;
    }}
}}
'''


def _typescript_handler(ms: dict[str, Any]) -> str:
    name = ms.get("name", "unknown")
    service_id = ms.get("service_id", "unknown")
    framework = ms.get("framework", "NestJS")
    return f'''/**
 * {name} — Microservice Handler
 * Service ID: {service_id}
 * Framework: {framework}
 * Generated by WorldMaker Code Generator
 */

// Metadata for static analysis / AI discovery
export const __metadata__ = {{
  microservice: "{name}",
  service_id: "{service_id}",
  language: "typescript",
  framework: "{framework}",
}};

interface Event {{
  action: string;
  data: Record<string, unknown>;
}}

interface Response {{
  status: string;
  action: string;
  result?: Record<string, unknown>;
  error?: string;
}}

export function healthCheck(): Record<string, string> {{
  return {{
    status: "healthy",
    service: "{name}",
    timestamp: new Date().toISOString(),
  }};
}}

export function handleEvent(event: Event): Response {{
  const {{ action = "default", data = {{}} }} = event;

  console.log(`Processing action=${{action}} for {name}`);

  try {{
    const result = process(action, data);
    return {{ status: "success", action, result }};
  }} catch (err) {{
    console.error(`Handler error in {name}:`, err);
    return {{ status: "error", action, error: String(err) }};
  }}
}}

function process(action: string, data: Record<string, unknown>): Record<string, unknown> {{
  return {{
    processed_by: "{name}",
    action,
    item_count: Object.keys(data).length,
    timestamp: new Date().toISOString(),
  }};
}}

// Local test
if (require.main === module) {{
  console.log(JSON.stringify(healthCheck(), null, 2));
  console.log(JSON.stringify(handleEvent({{ action: "test", data: {{ key: "value" }} }}), null, 2));
}}
'''


def _rust_handler(ms: dict[str, Any]) -> str:
    name = ms.get("name", "unknown")
    service_id = ms.get("service_id", "unknown")
    return f'''// {name} — Microservice Handler
// Service ID: {service_id}
// Generated by WorldMaker Code Generator

use std::collections::HashMap;
use std::time::SystemTime;

/// Metadata for static analysis / AI discovery
pub fn metadata() -> HashMap<&'static str, &'static str> {{
    let mut m = HashMap::new();
    m.insert("microservice", "{name}");
    m.insert("service_id", "{service_id}");
    m.insert("language", "rust");
    m.insert("framework", "{ms.get("framework", "Actix")}");
    m
}}

pub fn health_check() -> HashMap<String, String> {{
    let mut resp = HashMap::new();
    resp.insert("status".into(), "healthy".into());
    resp.insert("service".into(), "{name}".into());
    resp.insert("timestamp".into(), format!("{{:?}}", SystemTime::now()));
    resp
}}

pub fn handle_event(action: &str, data: &HashMap<String, String>) -> HashMap<String, String> {{
    println!("Processing action={{}} for {name}", action);

    let mut result = HashMap::new();
    result.insert("processed_by".into(), "{name}".into());
    result.insert("action".into(), action.to_string());
    result.insert("item_count".into(), data.len().to_string());
    result.insert("status".into(), "success".into());
    result
}}

fn main() {{
    let health = health_check();
    println!("Health: {{:?}}", health);

    let mut data = HashMap::new();
    data.insert("key".into(), "value".into());
    let result = handle_event("test", &data);
    println!("Result: {{:?}}", result);
}}
'''


def _kotlin_handler(ms: dict[str, Any]) -> str:
    name = ms.get("name", "unknown")
    service_id = ms.get("service_id", "unknown")
    return f'''/**
 * {name} — Microservice Handler
 * Service ID: {service_id}
 * Generated by WorldMaker Code Generator
 */
package com.worldmaker

import java.time.Instant

// Metadata for static analysis / AI discovery
val metadata = mapOf(
    "microservice" to "{name}",
    "service_id" to "{service_id}",
    "language" to "kotlin",
    "framework" to "{ms.get("framework", "Ktor")}"
)

fun healthCheck(): Map<String, String> = mapOf(
    "status" to "healthy",
    "service" to "{name}",
    "timestamp" to Instant.now().toString()
)

fun handleEvent(event: Map<String, Any>): Map<String, Any> {{
    val action = event.getOrDefault("action", "default") as String
    @Suppress("UNCHECKED_CAST")
    val data = event.getOrDefault("data", emptyMap<String, Any>()) as Map<String, Any>

    println("Processing action=$action for {name}")

    return try {{
        val result = process(action, data)
        mapOf("status" to "success", "action" to action, "result" to result)
    }} catch (e: Exception) {{
        mapOf("status" to "error", "action" to action, "error" to (e.message ?: "unknown"))
    }}
}}

private fun process(action: String, data: Map<String, Any>): Map<String, Any> = mapOf(
    "processed_by" to "{name}",
    "action" to action,
    "item_count" to data.size,
    "timestamp" to Instant.now().toString()
)

fun main() {{
    println(healthCheck())
    println(handleEvent(mapOf("action" to "test", "data" to mapOf("key" to "value"))))
}}
'''


# ── Handler Dispatch ─────────────────────────────────────────────────────

HANDLER_GENERATORS: dict[str, Any] = {
    "python": _python_handler,
    "go": _go_handler,
    "java": _java_handler,
    "typescript": _typescript_handler,
    "rust": _rust_handler,
    "kotlin": _kotlin_handler,
}


def generate_handler(ms: dict[str, Any]) -> str:
    """Generate handler source code for a microservice."""
    lang = ms.get("language", "python")
    gen = HANDLER_GENERATORS.get(lang, _python_handler)
    return gen(ms)


# ── Dependency File Templates ────────────────────────────────────────────

def generate_deps(ms: dict[str, Any]) -> str:
    """Generate dependency file content for a microservice."""
    lang = ms.get("language", "python")
    name = ms.get("name", "unknown")
    framework = ms.get("framework", "")

    if lang == "python":
        return f"""# {name} dependencies
fastapi>=0.104.0
uvicorn>=0.24.0
pydantic>=2.5.0
structlog>=23.2.0
"""
    elif lang == "go":
        return f"""module github.com/org/{name}

go 1.22

require (
\tgithub.com/gin-gonic/gin v1.9.1
\tgo.uber.org/zap v1.27.0
)
"""
    elif lang == "java":
        return f"""<?xml version="1.0" encoding="UTF-8"?>
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.worldmaker</groupId>
  <artifactId>{name}</artifactId>
  <version>1.0.0</version>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.2.0</version>
  </parent>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
  </dependencies>
</project>
"""
    elif lang == "typescript":
        return f"""{{"name": "{name}", "version": "1.0.0", "private": true,
  "dependencies": {{
    "@nestjs/core": "^10.3.0",
    "@nestjs/common": "^10.3.0",
    "@nestjs/platform-express": "^10.3.0",
    "reflect-metadata": "^0.2.1",
    "rxjs": "^7.8.1"
  }},
  "devDependencies": {{
    "typescript": "^5.3.0",
    "@types/node": "^20.10.0"
  }}
}}
"""
    elif lang == "rust":
        return f"""[package]
name = "{name}"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
tokio = {{ version = "1", features = ["full"] }}
"""
    elif lang == "kotlin":
        return f"""plugins {{
    kotlin("jvm") version "1.9.22"
    id("io.ktor.plugin") version "2.3.7"
}}

group = "com.worldmaker"
version = "1.0.0"

repositories {{
    mavenCentral()
}}

dependencies {{
    implementation("io.ktor:ktor-server-core-jvm")
    implementation("io.ktor:ktor-server-netty-jvm")
    implementation("ch.qos.logback:logback-classic:1.4.14")
}}
"""
    return f"# {name} dependencies\n"


# ── Dockerfile Template ──────────────────────────────────────────────────

def generate_dockerfile(ms: dict[str, Any]) -> str:
    """Generate a multi-stage Dockerfile for a microservice."""
    lang = ms.get("language", "python")
    name = ms.get("name", "unknown")
    tmpl = LANGUAGE_TEMPLATES.get(lang, LANGUAGE_TEMPLATES["python"])
    base = tmpl["dockerfile_base"]
    handler = tmpl["handler_file"]
    dep_file = tmpl["dep_file"]

    if lang == "python":
        return f"""# {name} Dockerfile
FROM {base} AS base
WORKDIR /app
COPY {dep_file} .
RUN pip install --no-cache-dir -r {dep_file}
COPY {handler} .
EXPOSE 8080
CMD ["python", "{handler}"]
"""
    elif lang == "go":
        return f"""# {name} Dockerfile
FROM {base} AS builder
WORKDIR /app
COPY {dep_file} .
RUN go mod download
COPY {handler} .
RUN CGO_ENABLED=0 go build -o /app/server {handler}

FROM alpine:3.19
COPY --from=builder /app/server /server
EXPOSE 8080
CMD ["/server"]
"""
    elif lang == "java":
        return f"""# {name} Dockerfile
FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /app
COPY {dep_file} .
COPY {handler} src/main/java/
RUN mvn package -DskipTests

FROM {base}
COPY --from=builder /app/target/*.jar /app.jar
EXPOSE 8080
CMD ["java", "-jar", "/app.jar"]
"""
    elif lang == "typescript":
        return f"""# {name} Dockerfile
FROM {base} AS builder
WORKDIR /app
COPY {dep_file} .
RUN npm ci
COPY {handler} .
RUN npx tsc {handler}

FROM {base}
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/*.js .
EXPOSE 8080
CMD ["node", "handler.js"]
"""
    elif lang == "rust":
        return f"""# {name} Dockerfile
FROM {base} AS builder
WORKDIR /app
COPY {dep_file} .
COPY {handler} src/
RUN cargo build --release

FROM debian:bookworm-slim
COPY --from=builder /app/target/release/{name} /usr/local/bin/
EXPOSE 8080
CMD ["{name}"]
"""
    elif lang == "kotlin":
        return f"""# {name} Dockerfile
FROM gradle:8.5-jdk21 AS builder
WORKDIR /app
COPY {dep_file} .
COPY {handler} src/main/kotlin/
RUN gradle shadowJar

FROM {base}
COPY --from=builder /app/build/libs/*-all.jar /app.jar
EXPOSE 8080
CMD ["java", "-jar", "/app.jar"]
"""
    return f"FROM {base}\nWORKDIR /app\nCOPY . .\nEXPOSE 8080\n"


# ── README Template ──────────────────────────────────────────────────────

def generate_readme(ms: dict[str, Any]) -> str:
    """Generate a README.md with microservice metadata."""
    name = ms.get("name", "unknown")
    lang = ms.get("language", "unknown")
    framework = ms.get("framework", "unknown")
    service_id = ms.get("service_id", "unknown")
    container_image = ms.get("container_image", "N/A")

    return f"""# {name}

> Auto-generated by WorldMaker Code Generator

| Field | Value |
|-------|-------|
| **Language** | {lang} |
| **Framework** | {framework} |
| **Service ID** | `{service_id}` |
| **Container Image** | `{container_image}` |
| **Status** | {ms.get("status", "active")} |

## Build

```bash
docker build -t {name} .
docker run -p 8080:8080 {name}
```

## Endpoints

- `GET /health` — Health check
- `POST /handle` — Main event handler
"""
